// <auto-generated />
using System;
using Feasablty_study.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Feasablty_study.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220814184127_last version")]
    partial class lastversion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Feasablty_study.Models.Competitors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmounrAdded")
                        .HasColumnType("int");

                    b.Property<string>("CompetitorsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompetitorsPrice")
                        .HasColumnType("float");

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("Products")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("Feasablty_study.Models.Construction_and_buliding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuildingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<float>("PricePerMeter")
                        .HasColumnType("real");

                    b.Property<float>("TotalArea")
                        .HasColumnType("real");

                    b.Property<float>("TotalPriceArea")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Construction_and_buliding");
                });

            modelBuilder.Entity("Feasablty_study.Models.Establishment_expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Establishment_expenses");
                });

            modelBuilder.Entity("Feasablty_study.Models.Expected_revenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyQusntity")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.Property<float>("TotalMonthlyPrice")
                        .HasColumnType("real");

                    b.Property<float>("TotalYearlyPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Expected_revenue");
                });

            modelBuilder.Entity("Feasablty_study.Models.Feasibility_study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feasibility_studies");
                });

            modelBuilder.Entity("Feasablty_study.Models.Government_fees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Government_fees");
                });

            modelBuilder.Entity("Feasablty_study.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("LicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licenses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("Feasablty_study.Models.Machinery_Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Machinery_Equipment");
                });

            modelBuilder.Entity("Feasablty_study.Models.Manpower_workforce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MonthlySalary")
                        .HasColumnType("real");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<float>("TotalMonthlySalary")
                        .HasColumnType("real");

                    b.Property<float>("TotalYearlySalary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Manpower_workforce");
                });

            modelBuilder.Entity("Feasablty_study.Models.Market_study", b =>
                {
                    b.Property<int>("FeasibilityStudyId")
                        .HasColumnType("int");

                    b.Property<string>("AvailbleOpportunity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketGap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointsOfEwakness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLocationOnTheMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrengthPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetMarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Threats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalExpected_revenue")
                        .HasColumnType("real");

                    b.Property<float>("TotalMarketing_Activity")
                        .HasColumnType("real");

                    b.HasKey("FeasibilityStudyId");

                    b.ToTable("Market_study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Marketing_Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Marketing_Activity");
                });

            modelBuilder.Entity("Feasablty_study.Models.Preliminary_study", b =>
                {
                    b.Property<int>("FeasibilityStudyId")
                        .HasColumnType("int");

                    b.Property<string>("CteristicsOfTheProjectArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactorsRepresentedOnIncreasedDemand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactorsRepresentedOnLowDemand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageOfTheProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectObjectives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisionOfTheProject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeasibilityStudyId");

                    b.ToTable("Preliminary_study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Public_benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Benefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<float>("MonthlyCost")
                        .HasColumnType("real");

                    b.Property<float>("YearlyCost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Public_benefit");
                });

            modelBuilder.Entity("Feasablty_study.Models.Raw_materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PriceOfUnity")
                        .HasColumnType("real");

                    b.Property<int>("QuantityRequiredMonthly")
                        .HasColumnType("int");

                    b.Property<float>("TotalPriceQuantityMonthly")
                        .HasColumnType("real");

                    b.Property<float>("TotalPriceQuantityYearly")
                        .HasColumnType("real");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Raw_materials");
                });

            modelBuilder.Entity("Feasablty_study.Models.Rentals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("RentalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("RentalYearly")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Feasablty_study.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DangerReductionStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionDangerReduece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Feasibility_StudyId")
                        .HasColumnType("int");

                    b.Property<string>("TypeRisk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Feasibility_StudyId");

                    b.ToTable("Risk");
                });

            modelBuilder.Entity("Feasablty_study.Models.Support_Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("Feasablty_study.Models.Technical_Study", b =>
                {
                    b.Property<int>("FeasibilityStudyId")
                        .HasColumnType("int");

                    b.Property<float>("TotalConstruction_and_buliding")
                        .HasColumnType("real");

                    b.Property<float>("TotalEstablishment_expenses")
                        .HasColumnType("real");

                    b.Property<float>("TotalGovernment_fees")
                        .HasColumnType("real");

                    b.Property<float>("TotalMachinery_Equipment")
                        .HasColumnType("real");

                    b.Property<float>("TotalManpower_workforce")
                        .HasColumnType("real");

                    b.Property<float>("TotalPublic_benefit")
                        .HasColumnType("real");

                    b.Property<float>("TotalRaw_materials")
                        .HasColumnType("real");

                    b.Property<float>("TotalRentals")
                        .HasColumnType("real");

                    b.HasKey("FeasibilityStudyId");

                    b.ToTable("Technical_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Feasablty_study.Models.Competitors", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("competitors")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Construction_and_buliding", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("construction_And_Bulidings")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Establishment_expenses", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("establishment_Expenses")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Expected_revenue", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("expected_Revenues")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Feasibility_study", b =>
                {
                    b.HasOne("Feasablty_study.Models.User", "user")
                        .WithMany("Feasibility_Studies")
                        .HasForeignKey("UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Feasablty_study.Models.Government_fees", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("Government_Fees")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.License", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("licenses")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Machinery_Equipment", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("machinery_Equipment")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Manpower_workforce", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("Manpower_Workforces")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Market_study", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "feasibility_study")
                        .WithOne("market_Study")
                        .HasForeignKey("Feasablty_study.Models.Market_study", "FeasibilityStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("feasibility_study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Marketing_Activity", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("marketing_Activities")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Preliminary_study", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "feasibility_study")
                        .WithOne("Preliminary_study")
                        .HasForeignKey("Feasablty_study.Models.Preliminary_study", "FeasibilityStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("feasibility_study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Public_benefit", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("public_Benefits")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Raw_materials", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("raw_Materials")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Rentals", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("rentals")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Risk", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "Feasibility_Study")
                        .WithMany("risks")
                        .HasForeignKey("Feasibility_StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feasibility_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.Support_Messages", b =>
                {
                    b.HasOne("Feasablty_study.Models.User", "user")
                        .WithMany("messages")
                        .HasForeignKey("UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Feasablty_study.Models.Technical_Study", b =>
                {
                    b.HasOne("Feasablty_study.Models.Feasibility_study", "feasibility_study")
                        .WithOne("technical_Study")
                        .HasForeignKey("Feasablty_study.Models.Technical_Study", "FeasibilityStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("feasibility_study");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Feasablty_study.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Feasablty_study.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feasablty_study.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Feasablty_study.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feasablty_study.Models.Feasibility_study", b =>
                {
                    b.Navigation("competitors");

                    b.Navigation("construction_And_Bulidings");

                    b.Navigation("establishment_Expenses");

                    b.Navigation("expected_Revenues");

                    b.Navigation("Government_Fees");

                    b.Navigation("licenses");

                    b.Navigation("machinery_Equipment");

                    b.Navigation("Manpower_Workforces");

                    b.Navigation("market_Study");

                    b.Navigation("marketing_Activities");

                    b.Navigation("Preliminary_study");

                    b.Navigation("public_Benefits");

                    b.Navigation("raw_Materials");

                    b.Navigation("rentals");

                    b.Navigation("risks");

                    b.Navigation("technical_Study");
                });

            modelBuilder.Entity("Feasablty_study.Models.User", b =>
                {
                    b.Navigation("Feasibility_Studies");

                    b.Navigation("messages");
                });
#pragma warning restore 612, 618
        }
    }
}
